### ISSUE TITLE
OpenStack pike support 

### ISSUE THREAD

**Issue by tjyang** [ManageIQ/manageiq-providers-openstack#134]
Hi 

I am opening up this issue to track [this issue reported in talk forum](http://talk.manageiq.org/t/does-manageiq-support-openstack-pike-version/2832/3).

[fog/opstack issue 315  marked openstack pike is supported in version v.0.1.22](https://github.com/fog/fog-openstack/issues/315)

**Comment by aufi** [comment]
Hi, the issue should have been resolved in https://github.com/ManageIQ/manageiq-providers-openstack/pull/129 (merged, not released yet).

**Comment by tjyang** [comment]
@aufi, thanks for the resolution info.
