### ISSUE TITLE
Create volume does not work from Manage Fine-3

### ISSUE THREAD

**Issue by dikonoor** [ManageIQ/manageiq-providers-openstack#140]
I am using ManageIQ fine-3 with OpenStack Ocata. I am able to register latter as a Cloud Provider and perform perform operations like deploy , VM lifecycle operations etc. However, when I try to create a new volume , it fails (I tried the same steps using the same OpenStack instance as the provider and volume creation works fine). 

Steps Followed:
From the MIQ UI >> storage>>block storage >> managers >> click on the specific manager >> click on cloud managers >> add a new cloud volume (from add configuration)

The above launches a page with 3 fields namely storage provider , volume name and size. The storage provider drop down is disabled. Upon filling the volume name and size, we are taken to a page that shows this:

Unexpected error encountered

Errors in Management Engine can be caused by:

① Accessing Management Engine from multiple tabs or windows of the same browser on a single machine. Close any duplicate browser sessions, then select an option from the menu.
② Pressing the back button during a session. 
      Close any duplicate browser sessions, then select an option from the menu.
③ An internal system error. 
      Please contact your administrator for assistance.

Error text:
undefined method `my_zone' for nil:NilClass [cloud_volume/create]

I see no errors in emv.log. but the production.log has the following:

[volume_create_error.txt](https://github.com/ManageIQ/manageiq-providers-openstack/files/1433723/volume_create_error.txt)

**Comment by mansam** [comment]
I can reproduce this in Fine-3, but it appears to fixed in Fine-4. Could you please confirm whether you still have that problem in Fine-4?

**Comment by dikonoor** [comment]
@mansam , I am yet to check in Fine-4. Will try and let you know shortly.

**Comment by dikonoor** [comment]
I tried in Fine-4 and it's fixed.
