### ISSUE TITLE
OpenStack Glance v2 Private images not visible at MIQ

### ISSUE THREAD

**Issue by dikonoor** [ManageIQ/manageiq-providers-openstack#142]
**Environment**
Found in Euwe, Fine-2 , Fine-3 and Fine-4   with OpenStack Ocata 
Gaprishdanavalli Beta with OpenStack Pike

Keystone v3

**Steps to Reproduce**
1. Install OpenStack and create a new project/tenant named 'project1' . 
2. Create a new user named 'user1' and give 'user1' admin role to 'project1'. (Please note that the same steps were later on repeated with a project named 'admin',where user1 has admin role against admin project and the results were the same).
3. Using user1, create one image inside 'project1'. By default it creates a private image. 
4. From MIQ , add this OpenStack instance as a Cloud Provider. Click on the provider (after waiting for few minutes) to view the summary page, which shows up all the other inventory correctly. Image is listed as 0.
5. When I go back and change visibility of the image to public, it shows up at MIQ. When I toggle it back to private, it disappears again.
6. The steps above were repeated with a project named 'admin' and a user named 'admin that was given admin role against 'admin' project (admin(user)<->admin(project)<->admin(role)). The results were the same.

This is a bad bug because it makes an end-user or operator go back and forth between a cloud provider and ManageIQ.

**Comment by dikonoor** [comment]
I checked in the beta release of Gaprishdanvili . Still seeing the problem.

**Comment by mansam** [comment]
A few questions to assist with troubleshooting:

1). Which version of Keystone are you using to connect to Openstack from ManageIQ?
2). Are you connecting to Openstack with the same credentials you used to create the private image?
3). Does the project itself have the admin role, in addition to the user having the admin role?

**Comment by dikonoor** [comment]
1) Keystone v3

2) Yes. I created a new project in Openstack. Let's call it 'project1'. I created a new user. Let's call it 'user1'. I gave admin role for user1 against project1. In OpenStack , I created an image with this user1 within project1. Images are anyway project-scoped resources and have a project_id associated with it. I added OpenStack as a cloud provider to ManageIQ (Like I mentioned, above, I tried this in all the recent releases including master) by giving credentials as user1.

3) I did not follow the question. In OpenStack a role assignment is made for a user against a project. The project itself cannot have an admin role. It's always actor-role-project(or domain) assignment, where actor can be a user or group. In short, I gave admin role to user1 within the scope of project1.

**Comment by mansam** [comment]
Sorry for the incoherent question, I misread the documentation I was looking at. When the image is set to private, can you confirm that it is visible when running `glance image-list` with the credentials you use to connect the provider?

**Comment by dikonoor** [comment]
@mansam yes..the images get listed. glance image-list lists images of visibility public and private (it lists images that belongs to the project that was used for authentication). glance image-show <image-uuid> shows the below.

+----------------------+----------------------------------------------------------------------------------+
| Property             | Value                                                                            |
+----------------------+----------------------------------------------------------------------------------+
| architecture         | ppc64                                                                            |
| bdm_v2               | true                                                                             |
| block_device_mapping | 
| checksum             | d41d8cd98f00b204e9800998ecf8427e                                                 |
| container_format     | bare                                                                             |
| created_at           | 2017-11-22T03:43:36Z                                                             |
| disk_format          | raw                                                                              |
| endianness           | xxx                                                                       |
| hypervisor_type      | xxx                                                                             |
| id                   | e314e89a-f580-49e2-8b3b-950a8f5bd664                                             |
| min_disk             | 1                                                                                |
| min_ram              | 0                                                                                |
| name                 | jin_image                                                                        |
| os_distro            | xxx                                                                             |
| owner                | 0f1753e414054f55995ad1e503d323a7                                                 |
| protected            | False                                                                            |
| root_device_name     | /dev/sda                                                                         |
| size                 | 0                                                                                |
| status               | active                                                                           |
| tags                 | []                                                                               |
| updated_at           | 2017-11-22T03:43:37Z                                                             |
| virtual_size         | None                                                                             |
| visibility           | private                                                                          |
+----------------------+----------------------------------------------------------------------------------+

**Comment by dikonoor** [comment]
I see that from Gaprishdanvili onwards, the cloud provider summary page shows the below error if there's atleast one private image in the openstack project.

Steps:
1. Created project and gave a user admin role. 
2. Created 2 images - one public and the other private
3. Discover OpenStack (Pike) as a cloud provider. OpenStack is successfully added
4. Wait for few minutes and click on the cloud provider to see error:

Status
Default Credentials	Valid
Last Refresh	
Error - 22 Minutes Ago
Expected([200, 204]) <=> Actual(403 Forbidden) excon.error.response :body => "{\"message\": \"Error fetchi...
Last Refresh Date	2017-12-07 05:28:36 UTC


evm.log shows the below:

[----] E, [2017-12-07T00:16:32.750851 #92833:fb10d0] ERROR -- : MIQ(ManageIQ::Providers::Openstack::CloudManager::Refresher#refresh) EMS: [pvc_140], id: [35] Refresh failed
[----] E, [2017-12-07T00:16:32.751278 #92833:fb10d0] ERROR -- : [Excon::Error::Forbidden]: Expected([200, 204]) <=> Actual(403 Forbidden)
excon.error.response
  :body          => "{\"message\": \"Error fetching members of image e314e89a-f580-49e2-8b3b-950a8f5bd664: Only shared images have members.<br /><br />\\n\\n\\n\", \"code\": \"403 Forbidden\", \"title\": \"Forbidden\"}"
  :cookies       => [
  ]
  :headers       => {
    "Content-Length"         => "182"
    "Content-Type"           => "application/json"
    "Date"                   => "Thu, 07 Dec 2017 05:16:32 GMT"
    "Server"                 => "Apache"
    "Vary"                   => "User-Agent"
    "X-Openstack-Request-Id" => "req-15c77f54-9546-451b-96b8-0ec1645e47da"
  }
  :host          => "x.x.x.x@x.com"
  :local_address => "y.y.y.y"
  :local_port    => 35846
  :path          => "/v2/images/e314e89a-f580-49e2-8b3b-950a8f5bd664/members"
  :port          => 9292
  :reason_phrase => "Forbidden"
  :remote_ip     => "X.X.X.X"
  :status        => 403
  :status_line   => "HTTP/1.1 403 Forbidden\r\n"
  Method:[block in method_missing]
[--

********************************************************************************************

Once I go and change the image to be private , the cloud provider summary page looks fine


Status
--
Default Credentials | Valid
Last Refresh | Success - 3 Minutes Ago | Success - 3 Minutes Ago |  
Success - 3 Minutes Ago
 
Last Refresh Date | 2017-12-07 06:24:27 UTC

**Comment by dikonoor** [comment]
The steps above were repeated with a project named 'admin' and a user named 'admin that was given admin role against 'admin' project (admin(user)<->admin(project)<->admin(role)). The results were the same.

**Comment by dikonoor** [comment]
I am unable to reproduce this problem in the latest gaprishdanvili development build. I will wait for the official release to be out and validate against it before closing this.

**Comment by JPrause** [comment]
@dikonoor is this still a valid issue? If yes, let me know and I'll remove the stale label. If not can you close. If there's no update by next week, I'll be closing this issue.

**Comment by JPrause** [comment]
Closing issue. If you feel the issue needs to remain open, please either reopen or let me know and it will be reopened. 
@miq-bot close_issue
