### ISSUE TITLE
Instance Operating System displayed as Unknown for OpenStack Cloud provider

### ISSUE THREAD

**Issue by dikonoor** [ManageIQ/manageiq-providers-openstack#151]
I added a OpenStack as a cloud provider to MIQ and see the Operating System field against a VM displayed as "Unknown". I am on Fine-4. I see this problem discussed in different MIQ forums but haven't run into a bug that's already reporting this. 

Name | test1_new
IP Address | 172.28.0.7
MAC Address | fa:59:fa:a6:47:20
Container | openstack: 1 CPU (1 socket x 1 core), 4096 MB
Platform Tools | N/A
Operating System | unknown

**Comment by aufi** [comment]
Hi thanks for submitting the issue. Having few questions for better understanding:
 * what Operating system do you use on the Vm?
 * did SmartState Analysis run succesfully on the Vm?
 * what OpenStack version do you use?

**Comment by dikonoor** [comment]
@aufi smart State analysis runs successfully on the VM.

**Comment by JPrause** [comment]
@dikonoor is this still a valid issue? If yes, let me know and I'll remove the stale label. If not can you close. If there's no update by next week, I'll be closing this issue.

**Comment by JPrause** [comment]
Closing issue. If you feel the issue needs to remain open, please either reopen or let me know and it will be reopened. 
@miq-bot close_issue
