### ISSUE TITLE
ManageIQ logs piling up and eating up space

### ISSUE THREAD

**Issue by dikonoor** [ManageIQ/manageiq-providers-openstack#152]
I am using MIQ Fine-4 and see that even though the log rotation works fine and the log archives are created, they don't get purged automatically after few number of archives are created. I am not sure if MIQ has a setting to manage this. For now, I am having to delete all the log archives under /var/www/miq/vmdb/log manually, which is a pain because I have to periodically check for these and delete them.

**Comment by aufi** [comment]
Hi, thanks for message, not sure if it is a bug or it works as expected. Reassigning to main repo since OpenStack provider itself cannot change log rotation.

@miq-bot move_issue manageiq

**Comment by dikonoor** [comment]
@aufi , Sure. Thanks for moving it to the main repo.
