### ISSUE TITLE
ManageIQ expects user to have admin role again admin project in an OpenStack cloud provider

### ISSUE THREAD

**Issue by dikonoor** [ManageIQ/manageiq-providers-openstack#155]
**Environment:**
Tried in the following environments:
Euwe with OpenStack Ocata
Fine-3 / Fine-4 with OpenStack Ocata
Gaprishdanvili with OpenStack Pike

Steps:
1. Create a new user in OpenStack that has admin role against a new project. Let's call the project 'project1' and let's call the user as user 'user1'. So user 'xyz' now has admin role against project 'abc'.
2. Project 'project1' is within the default domain and there's only one project under this domain.
3. Login to MIQ and add this OpenStack instance as a Cloud provider (Leave the 'tenant mapping as disabled or not selected). 

The registration goes through fine. The cloud provider is added to MIQ. However, when we click on the cloud provider to view the Summary page , we see the following:

Status
--
**Default Credentials | Error**
Last Refresh | Success - 6 Minutes Ago | Success - 6 Minutes Ago

The fog.log is full of these:

[----] E, [2017-11-14T03:21:31.446584 #14901:3f9569d29130] ERROR -- : excon.error     #<Excon::Error::Unauthorized: Expected([201]) <=> Actual(401 Unauthorized)
excon.error.response
  :body          => "{\"error\": {\"message\": \"The request you have made requires authentication.\", \"code\": 401, \"title\": \"Unauthorized\"}}"
  :cookies       => [
  ]
  :headers       => {
    "Content-Length"         => "114"
    "Content-Type"           => "application/json"
    "Date"                   => "Tue, 14 Nov 2017 03:21:31 GMT"
    "Server"                 => "Apache"
    "Vary"                   => "X-Auth-Token"
    "WWW-Authenticate"       => "Keystone uri=\"https://x.x.x.x:5000\""
    "x-openstack-request-id" => "req-72ba0a56-0e71-4435-87b6-264017dfdaa5"
  }
  :host          => "x.x.x.x"
  :local_address => "172.17.0.2"
  :local_port    => 43002
  :path          => "/v3/auth/tokens"
  :port          => 5000
  :reason_phrase => "Unauthorized"
  :remote_ip     => "x.x.x.x"
  :status        => 401
  :status_line   => "HTTP/1.1 401 Unauthorized\r\n"

When I check against the keystone.log at OpenStack, I see this:

 User 0688b01e6439ca32d698d20789d52169126fb41fb1a4ddafcebb97d854e836c9 has no access to project admin _populate_roles /usr/lib/python2.7/site-packages/keystone/token/providers/common.py:339
2017-11-13 22:09:42.905 11716 WARNING keystone.common.wsgi [req-18a15765-964b-40c5-9ea9-aa94b5e5c026 - - - - -] Authorization failed. The request you have made requires authentication. from x.x.x.x

This effectively means that ManageIQ inherently assumes that the user used to register the cloud provider must have admin access to the project named 'admin'.  A community devstack instance gets created with projects like admin and demo by default but it would be a bug to assume that all OpenStack installations will always have an 'admin' project. For eg. , the OpenStack installation I use does not have a project named 'admin' . 

The problem reported here can be worked around by creating a project named 'admin on OpenStack and mapping a user to it.

**Comment by mansam** [comment]
I don't believe ManageIQ requires there to be a project named "admin", but I do believe it requires the Openstack user and the project they are a member of to both have the admin role. @aufi can correct me if I am mistaken.

**Comment by dikonoor** [comment]
@mansam , I had expected the same .I had expected ManageIQ to work fine , without any errors with a user that has admin role against any of the projects (under the domain that was provided as input)..but that doesn't seem to be the case. But there seems to be a bug somewhere that specifically looks for admin project. I guess this might be because Openstack has an admin project created by default and perhaps that's the default project and probably MangeIQ was always tested on that and it worked.

**Comment by dikonoor** [comment]
@mansam @aufi ,I tried this scenario in and Gaprishdanavalli with OpenStack Pike and this problem continues to exist. It forces a user to have admin role against a project named 'admin' in OpenStack .

Error at OpenStack Pike:

2017-12-06 06:55:45.330 32584 WARNING keystone.auth.core [req-927d7610-7391-48f8-aec3-0936cf07b435 - - - - -] Could not find project: admin.: ProjectNotFound: Could not find project: admin.
2017-12-06 06:55:45.330 32584 WARNING keystone.common.wsgi [req-927d7610-7391-48f8-aec3-0936cf07b435 - - - - -] Authorization failed. The request you have made requires authentication. from x.x.x.x: Unauthorized: The request you have made requires authentication.

2017-12-06 06:55:45.351 32584 INFO keystone.common.wsgi [req-77b846f4-8fb4-4d93-810a-b1fae765a5e3 - - - - -] POST https://x.x.x.x:5000/v3/auth/tokens

**Comment by mansam** [comment]
@dikonoor I have not been able to reproduce this problem so far. With a tenant named 'test_tenant_1" and a user "test_tenant_1_admin" who has the admin role, refresh works fine. One possible difference between our environments is that I still have a tenant named "admin", although the user my provider is configured with has no access to it. In order to help me troubleshoot, could you confirm whether this happens for you if there is a tenant named "admin" present in your environment, even if the user has no roles on it?

**Comment by dikonoor** [comment]
@mansam ,let me paste below how the role assignment looks like in my setup:

openstack role assignment list --names
+---------+--------------------+---------------------+---------------------+--------+-----------+
| Role    | User               | Group               | Project             | Domain | Inherited |
+---------+--------------------+---------------------+---------------------+--------+-----------+
| admin   | xyz@Default |                         | abc@Default |                | False     |
+---------+--------------------+---------------------+---------------------+--------+-----------+

I have a domain , which is the 'Default' domain; project abc . The reported problem can be observed even in cases where there's a project named 'admin' with no role assignment against it.

**Comment by dikonoor** [comment]
@mansam I am unable to reproduce this problem in the latest gaprishdanvili development build. I will wait for the official release to be out and validate against it before closing this.

**Comment by christomas1** [comment]
Hello @dikonoor, can you confirm if you reproduced the problem with the latest version (gaprishdanvili)?

**Comment by JPrause** [comment]
@dikonoor is this still a valid issue? If yes, let me know and I'll remove the stale label. If not can you close. If there's no update by next week, I'll be closing this issue.

**Comment by JPrause** [comment]
Closing issue. If you feel the issue needs to remain open, please either reopen or let me know and it will be reopened. 
@miq-bot close_issue

**Comment by jwcroppe** [comment]
@dikonoor Does this still remain a problem to your knowledge?
