### ISSUE TITLE
Wrong index for lazy find

### ISSUE THREAD

**Issue by Ladas** [ManageIQ/manageiq-providers-openstack#164]
@mansam I've noticed these

https://github.com/Ladas/manageiq-providers-openstack/blob/ce4cd9acf7c2c2f236503fa6bb972b8f4aee7d1e/app/models/manageiq/providers/openstack/inventory/parser/network_manager.rb#L32

https://github.com/Ladas/manageiq-providers-openstack/blob/ce4cd9acf7c2c2f236503fa6bb972b8f4aee7d1e/app/models/manageiq/providers/openstack/inventory/parser/network_manager.rb#L130

the orchestration_stack_by_resource_id returns a Fog object, but we need ems_ref string for the lazy find.

----

I am working on the internal indexes refacotrings, so then, we would see these fails.

**Comment by mansam** [comment]
Nice catch, thanks Ladas.
