### ISSUE TITLE
VM provisioning fails with placement options

### ISSUE THREAD

**Issue by dikonoor** [ManageIQ/manageiq-providers-openstack#178]
**Environment:**
Gaprishdanvili with OpenStack Pike
This problem is NOT found in Fine

Steps to Reproduce:
1. Select and image and click on Provision virtual machines.
2. In the Provision Instances pages, go to 'Environment' tab.
3. Uncheck 'Choose Automatically Option' under Placement and select a specific project from the 'Cloud Tenant' dropdown. We can notice that the 'Security Groups' dropdown automatically populates with a default value.

I don't have SDN setup in my environment and thus security groups have no relevance. Selecting security groups while provisioning VMs leads to failure due to this and thus I want to provision my instance without security groups. However, the drop drown does not provide an option to deselect security groups, due to which a security groups always gets selected and the deploy fails.

**Comment by aufi** [comment]
The _security group_ field is not required to provision a Vm, so it should be possible submit the provisioning form without the security group filled.

**Comment by JPrause** [comment]
@dikonoor is this still a valid issue? If yes, let me know and I'll remove the stale label. If not can you close. If there's no update by next week, I'll be closing this issue.

**Comment by JPrause** [comment]
Closing issue. If you feel the issue needs to remain open, please either reopen or let me know and it will be reopened. 
@miq-bot close_issue
