### ISSUE TITLE
MIQ doesn't have provision to attach network to a VM post provisioning

### ISSUE THREAD

**Issue by dikonoor** [ManageIQ/manageiq-providers-openstack#179]
**Environment**
Euwe, Fine with OpenStack Ocata

Steps:
1. Install OpenStack. 
2. Create a new user named 'user1' and give 'user1' admin role to 'project1'. 'project1' is created under the default domain. There are no other projects in this domain.
3. Discover OpenStack as a Cloud Provider from ManageIQ.
4. Go to Cloud summary page, select image and click on provision VM.

There are two problems:
1) When a VM is being provisioned, the network has to be selected from a dropdown and only one network can be selected, which basically means that a VM from MIQ can be provisioned only with one network.
2) I don't see an option in MIQ UI to attach a network to the VM after provisioning.

OpenStack provides the option of specifying multiple networks to a VM at the time of provisioning and to add network after provisioning, both of which are not possible in ManageIQ currently.

**Comment by dikonoor** [comment]
I am not sure if there are other ways to do this from MIQ other than from the UI. If so, please let me know.

**Comment by JPrause** [comment]
@dikonoor is this still a valid issue? If yes, let me know and I'll remove the stale label. If not can you close. If there's no update by next week, I'll be closing this issue.

**Comment by JPrause** [comment]
Closing issue. If you feel the issue needs to remain open, please either reopen or let me know and it will be reopened. 
@miq-bot close_issue
