### ISSUE TITLE
Abstract ::Settings.ems_refresh.openstack into options method

### ISSUE THREAD

**Issue by mansam** [ManageIQ/manageiq-providers-openstack#191]

**Comment by JPrause** [comment]
@mansam is this still a valid issue? If yes, let me know and I'll remove the stale label. If not can you close. If there's no update by next week, I'll be closing this issue.

**Comment by JPrause** [comment]
Closing issue. If you feel the issue needs to remain open, please either reopen or let me know and it will be reopened. 
@miq-bot close_issue
