### ISSUE TITLE
ManageIQ does not have support for secure communication with OpenStack message queue

### ISSUE THREAD

**Issue by dikonoor** [ManageIQ/manageiq-providers-openstack#199]
Environment:
ManageIQ Gaprishdanvili with OpenStack Pike
ManageIq Fine with OpenStack Ocata

While registering a new OpenStack based cloud provider, MIQ provides options to connect using ceilometer or AMQP. In the AMQP, the security protocol drop down lists only non-SSL option. Connection from MIQ to a OpenStack message queue (rabbitmq) connects fine over amqp. However, enterprise customers will always configure message queue only in the secure mode(amqps).

Connecting MIQ to a message queue configured in secure mode fails . This is because MIQ does not have the support for this. I assume the change required to add this support into MIQ will not be much and it will help all OpenStack installations that use secure queue.

**Comment by JPrause** [comment]
@dikonoor is this still a valid issue? If yes, let me know and I'll remove the stale label. If not can you close. If there's no update by next week, I'll be closing this issue.

**Comment by JPrause** [comment]
Closing issue. If you feel the issue needs to remain open, please either reopen or let me know and it will be reopened. 
@miq-bot close_issue

**Comment by dikonoor** [comment]
@JPrause Sorry for the much delayed response on this. I couldn't get to trying it with the latest release before this. I have a CF 5.0 beta which I am using with OpenStack Stein (couple of weeks back Train was release and OpenStack master is going through Ussuri). My OpenStack instance as in the previous case uses RabbitMQ running in secure mode at port 5671. CF provides option only for non-SSL communication to RabbitMQ. So when I attempt to add my OpenStack based cloud provider to CF, it complains with the below error:

[----] I, [2019-11-15T01:59:29.444962 #3974:e4af48]  INFO -- : MIQ(MiqGenericWorker::Runner#get_message_via_drb) Message id: [1000001176649], MiqWorker id: [1000000006428], Zone: [default], Role: [ems_operations], Server: [], MiqTask id: [1000000016740], Ident: [generic], Target id: [], Instance id: [], Task id: [], Command: [ManageIQ::Providers::Openstack::CloudManager.raw_connect?], Timeout: [600], Priority: [100], State: [dequeue], Deliver On: [], Data: [], Args: ["********", {:name=>"ABVC", :provider_region=>"RegionOne", :api_version=>"v3", :default_security_protocol=>"ssl", :keystone_v3_domain_id=>"default", :default_hostname=>"9.xxx.xxx.xx", :default_api_port=>"5000", :default_userid=>"xxx", :event_stream_selection=>"amqp"}], Dequeued in: [3.198537765] seconds
[----] I, [2019-11-15T01:59:29.445144 #3974:e4af48]  INFO -- : MIQ(MiqQueue#deliver) Message id: [1000001176649], Delivering...
[----] I, [2019-11-15T01:59:29.472866 #3974:e4af48]  INFO -- : MIQ(MiqTask#update_status) Task: [1000000016740] [Active] [Ok] [Task starting]
[----] I, [2019-11-15T01:59:29.485645 #3974:e4af48]  INFO -- : MIQ(OpenstackRabbitEventMonitor.test_connection) Failed testing rabbit amqp connection: Authentication with RabbitMQ failed. Please check your connection settings. Username: guest, vhost: /, password length: 8

The OpenStack cloud provider is not successfully added to CF because connection to RabbitMQ fails. My RabbitMQ does not accept insecure communication protocol. My config looks like this:

[
 {rabbit, [
  {tcp_listeners, [] },
  {handshake_timeout, 30000},
  {ssl_handshake_timeout, 30000},
  {ssl_listeners, [5671]},
  {ssl_options, [
   {versions, ['tlsv1.2']},
   {cacertfile, "/etc/pki/messages/ca/cacert.pem"},
   {certfile, "/etc/pki/messages/server/cert.pem"},
   {keyfile, "/etc/pki/messages/server/private/key.pem"},
   {verify, verify_peer},   {fail_if_no_peer_cert, true},
   {ciphers,[{ecdhe_rsa,aes_256_cbc,sha384,sha384}]}]}
 ]}

The keystone credentials used for authentication is still valid. And I can see in the Keystone logs that that goes through fine.

**Comment by dikonoor** [comment]
@JPrause , I am unable to reopen this issue. Please reopen.

**Comment by dikonoor** [comment]
Also, ceilometer is no longer a supported or valid service. So there is no way CF will be able to connect to recent deployments of OpenStack and they will completely rely on RabbitMQ and this is thus a blocker.
