### ISSUE TITLE
Instance Snapshots are not part of refresh

### ISSUE THREAD

**Issue by tzumainn** [ManageIQ/manageiq-providers-openstack#21]
Instance snapshots are not part of refresh; instead, they are manually created/removed in cloud_manager.rb methods.

**Comment by JPrause** [comment]
@tzumainn is this still a valid issue? If yes, let me know and I'll remove the stale label. If not can you close. If there's no update by next week, I'll be closing this issue.

**Comment by JPrause** [comment]
Closing issue. If you feel the issue needs to remain open, please either reopen or let me know and it will be reopened. 
@miq-bot close_issue
