### ISSUE TITLE
Cloud Networks need to be able to update vlan_transparent flag

### ISSUE THREAD

**Issue by gildub** [ManageIQ/manageiq-providers-openstack#230]
Network refresh parser can read the field but it can't be updated because not available yet in fog-openstack request `create_network` in https://github.com/fog/fog-openstack/blob/master/lib/fog/network/openstack/requests/create_network.rb#L5-L26

To be able to update the option the following 
- [ ] Patch fog-openstack accordingly
- [ ] Add the corresponding field to the UI form Cloud Networks in manageiq-ui-classic, both for creation and update.

**Comment by gildub** [comment]
@miq-bot assign gildub

**Comment by JPrause** [comment]
@gildub is this still a valid issue? If yes, let me know and I'll remove the stale label. If not can you close.
If there's no update by next week, I'll be closing this issue.

**Comment by gildub** [comment]
The VLAN transparent flag can only be setup during creation of the network. Once created it cannot be updated.
