### ISSUE TITLE
The Instance cannot be resized, current state has to be active or shutoff.

### ISSUE THREAD

**Issue by himdel** [ManageIQ/manageiq-providers-openstack#246]
When trying to resize an openstack instance, all I ever get is "The Instance cannot be resized, current state has to be active or shutoff.".

Even when the instance is indeed shut off (`raw_power_state === "off"`).

That's because we're comparing the `raw_power_state` value to *strings* `ACTIVE` and `SHUTOFF`, not the constants of the same name.

More: https://github.com/ManageIQ/manageiq/pull/9683#discussion_r172252937

**Comment by mansam** [comment]
I'm a little confused. The raw power states from Nova are "ACTIVE" and "SHUTOFF", so string comparison on the field `raw_power_state` should work, because that's what `raw_power_state` contains. The `power_state` column contains "on/"off", but that doesn't seem to be the field being compared here.

**Comment by himdel** [comment]
@mansam sorry, you're right, looks like I was confused. I must have looked at a Vm other than Openstack.

Confirmed you're right:

```
> ManageIQ::Providers::Openstack::CloudManager::Vm.pluck(:raw_power_state)
=> ["ACTIVE", "ACTIVE", "ACTIVE", "unknown", "unknown", "unknown", "ACTIVE", "unknown", "ACTIVE", "ACTIVE", "unknown", "ACTIVE", "unknown", "unknown", "ACTIVE", "ACTIVE", "ACTIVE", "ACTIVE", "unknown", "ACTIVE", "ACTIVE", "unknown", "unknown", "unknown", "unknown", "unknown", "ACTIVE", "unknown", "ACTIVE", "SHUTOFF", "unknown", "unknown", "ACTIVE", "unknown", "unknown", "unknown", "unknown", "unknown", "unknown", "unknown", "ACTIVE", "ACTIVE", "unknown", "unknown"]
```
