### ISSUE TITLE
Compatibility with Fine, Mitaka and admin project.

### ISSUE THREAD

**Issue by gianpietro1** [ManageIQ/manageiq-providers-openstack#291]
Hi,

I was wondering if this is the gem used by Fine-4 version too? or is it another project?

Thing is, I'm facing an issue when trying to add a Mitaka-based OpenStack environment as Cloud Provider, where Fine-4-based ManageIQ fails to do so.  
What we can see in the network flows, is:
1) ManageIQ tries to authenticate with 'admin' project before authenticating with domain scope. 
2) Mitaka-based OpenStack responds 'Project does not exist'
3) ManageIQ stops trying, so provider is not added.

With other, newer OpenStack versions:
1) ManageIQ tries to authenticate with 'admin' project before authenticating with domain scope. 
2) OpenStack responds 'The request you have made requires authentication'
3) ManageIQ continues trying with domain-scoped authentication, and provider is added successfully.

Any hint is welcomed, thanks!

**Comment by JPrause** [comment]
@gianpietro1 is this still a valid issue? If yes, let me know and I'll remove the stale label. If not can you close. If there's no update by next week, I'll be closing this issue.

**Comment by JPrause** [comment]
Closing issue. If you feel the issue needs to remain open, please either reopen or let me know and it will be reopened. 
@miq-bot close_issue
