### ISSUE TITLE
Support Integrate account domain and project domain separately

### ISSUE THREAD

**Issue by okamototk** [ManageIQ/manageiq-providers-openstack#294]
Currently, ManageIQ use account of integration domain and project domain are same. If we use LDAP for OpenStack, we need integration account in LDAP. But some of company prohibit such a acoount in company. Using personal account has risk to expose her/his private information to CloudForms administrators.

Again, problem is openstack provider use same domain for authentication and project.

https://github.com/ManageIQ/manageiq-providers-openstack/blob/master/lib/manageiq/providers/openstack/legacy/openstack_handle/handle.rb#L180

      # For identity ,there is only domain scope, with project_name nil
      opts[:openstack_project_name] = @project_name = tenant if tenant
      opts[:openstack_project_domain_id] = domain
      opts[:openstack_user_domain_id]    = domain
      opts[:openstack_region]            = region
 
Could you make both domain configurable independently?

**Comment by aufi** [comment]
Hi, thanks for submitting this issue. Could you elaborate on use-case for this feature? Using LDAP with Keystone backend is quite common, but I haven't heard about this case with different domains.

Since we are upstream, is it possible to test, that such change really fixes your problem (and there is not e.g. Keystone token creation problem)?

**Comment by okamototk** [comment]
Thank you for attention about the issue.

I want to use admin account in openstack default domain for provider because it's difficult to create admin account on customer/company LDAP.  Of course private LDAP and small company doesn't have problem.
Imagine if you install ManageIQ for huge company and organization. These company has a lot of security and information management policy.  It is quite difficult to change such policy. 

Assume using mycom-domain with LDAP, we need to create admin user account at mycom-domain in LDAP. OpenStack doesn't allow local account for LDAP domain. 
Of course LDAP must have admin user account, but it's domain is different from general user domain to hide admin account from general users.  Then OpenStack could't include LDAP admin account and user account in same doman.

If you have any doubt, please ask.

**Comment by JPrause** [comment]
@okamototk is this still a valid issue? If yes, let me know and I'll remove the stale label. If not can you close. If there's no update by next week, I'll be closing this issue.

**Comment by JPrause** [comment]
Closing issue. If you feel the issue needs to remain open, please either reopen or let me know and it will be reopened. 
@miq-bot close_issue
