### ISSUE TITLE
User tenant is invisible

### ISSUE THREAD

**Issue by okamototk** [ManageIQ/manageiq-providers-openstack#298]
I use ldap authentication and OpenStack domain. 
Then, user tenant is invisible.  In additional to, admin tenants are exposed to all users.
I found cause is following current_user_id always return admin id.

https://github.com/ManageIQ/manageiq-providers-openstack/blob/master/lib/manageiq/providers/openstack/legacy/openstack_handle/identity_delegate.rb#L28

      projects.all(:domain_id => @os_handle.domain_id, :user_id => current_user_id)

Any opinion?

**Comment by JPrause** [comment]
@okamototk is this still a valid issue? If yes, let me know and I'll remove the stale label. If not can you close. If there's no update by next week, I'll be closing this issue.

**Comment by JPrause** [comment]
Closing issue. If you feel the issue needs to remain open, please either reopen or let me know and it will be reopened. 
@miq-bot close_issue
