### ISSUE TITLE
provisioning from Glance template creates RAW volume

### ISSUE THREAD

**Issue by sleenavteca** [ManageIQ/manageiq-providers-openstack#308]
Hello, I am seeing a behavior where the cinder.volume.flows.manager.create_volume is creating as RAW when I go to provision an instance from an image.  When I provision from Horizon, I see cinder.volume.flows.manager.create_volume creates it as an Image.  What I'm seeing is:

ManageIQ:
`INFO cinder.volume.flows.manager.create_volume [req-caa7c2e9-40e8-4baa-ab40-d2b5afecddce f34779dfdc8e1f965866987a3aea715de08d87f6ffdd94dc3ec1c27935f665ff 53eb9db347a14bb580fdac1b744a911c - b5b5816a30fc4de2b62b9e16ae09a8c8 b5b5816a30fc4de2b62b9e16ae09a8c8] Volume 99167e3d-fcc3-418a-8840-781a8e671809: being created as raw with specification: {'status': u'creating', 'volume_size': 2, 'volume_name': 'volume-99167e3d-fcc3-418a-8840-781a8e671809'}`

Horizon:
`INFO cinder.volume.flows.manager.create_volume [req-81bd4ab2-78f7-4480-ab5b-b2ffd09e967a f34779dfdc8e1f965866987a3aea715de08d87f6ffdd94dc3ec1c27935f665ff 53eb9db347a14bb580fdac1b744a911c - b5b5816a30fc4de2b62b9e16ae09a8c8 b5b5816a30fc4de2b62b9e16ae09a8c8] Volume 38d28faa-ec36-4980-970d-fa60faef1372: being created as image with specification: {'status': u'creating', 'image_location': (u'file:///gpfs/gpctestfs/openstack/glance/a962b125-1b75-4eb0-a25e-210318a96450', [{u'url': u'file:///gpfs/gpctestfs/openstack/glance/a962b125-1b75-4eb0-a25e-210318a96450', u'metadata': {}}]), 'volume_size': 12, 'volume_name': 'volume-38d28faa-ec36-4980-970d-fa60faef1372', 'image_id': 'a962b125-1b75-4eb0-a25e-210318a96450', 'image_service': <cinder.image.glance.GlanceImageService object at 0x6fa5a90>, 'image_meta': {u'status': u'active', u'file': u'/v2/images/a962b125-1b75-4eb0-a25e-210318a96450/file', u'virtual_size': None, u'name': u'CentOS-7-x86_64-GenericCloud-1711', u'tags': [], u'container_format': u'bare', u'created_at': datetime.datetime(2017, 12, 14, 18, 57, 34, tzinfo=<iso8601.Utc>), u'disk_format': u'qcow2', u'updated_at': datetime.datetime(2018, 1, 18, 21, 25, 42, tzinfo=<iso8601.Utc>), u'visibility': u'private', u'locations': [{u'url': u'file:///gpfs/gpctestfs/openstack/glance/a962b125-1b75-4eb0-a25e-210318a96450', u'metadata': {}}], u'owner': u'53eb9db347a14bb580fdac1b744a911c', u'protected': False, u'id': u'a962b125-1b75-4eb0-a25e-210318a96450', u'min_ram': 0, u'checksum': u'317ecf7d1128e0e53cb285b8704dc3d3', u'min_disk': 0, u'direct_url': u'file:///gpfs/gpctestfs/openstack/glance/a962b125-1b75-4eb0-a25e-210318a96450', 'properties': {u'os': u'windows'}, u'size': 876740608}}`

Is this difference expected?  Is there a way to change how ManageIQ calls the API so it mimics Horizon?  Creating as raw is breaking for us, because of other issues we currently have with GPFS and assigning the file to the 'system' storage pool.  Provisioning via Horizon works.

**Comment by sleenavteca** [comment]
To expound on this, it doesn't look like ManageIQ is calling the glance API at all, and is instead trying to create a new raw volume instead of downloading the image and converting it.  Has anybody else seen this behavior?  Is Glance supported with gaprindashvili-3?

**Comment by JPrause** [comment]
@sleenavteca is this still a valid issue? If yes, let me know and I'll remove the stale label. If not can you close. If there's no update by next week, I'll be closing this issue.

**Comment by JPrause** [comment]
Closing issue. If you feel the issue needs to remain open, please either reopen or let me know and it will be reopened. 
@miq-bot close_issue
