### ISSUE TITLE
no mapping attribute between cloud and infra provider in api 

### ISSUE THREAD

**Issue by izapolsk** [ManageIQ/manageiq-providers-openstack#315]
when I add cloud OSP provider via ui, there is field with mapping to infra OSP provider.
I didn't manage to figure out how to fill in that field via rest.
As far as I see that attribute is missing in provider specific attributes  - 
https://github.com/ManageIQ/manageiq-providers-openstack/blob/17b926bf44d0f0d960b79d571a8435bd0aa4da82/app/models/manageiq/providers/openstack/cloud_manager.rb#L132

**Comment by aufi** [comment]
Hi, thanks for reporting. I'm not aware of most of REST API features, so it is possible that this part is missing.
There could be two causes - either try to use Providers object in API, but I don't know how API wants model Cloud/Infra managers within the Provider.
Or the option for Infra provider could be to added to the API.

**Comment by aufi** [comment]
@evgeny-chufarov Put there steps how to assign Infra provider with existing API calls, thanks!

**Comment by evgeny-chufarov** [comment]
Ok

вт, 24 июл. 2018 г., 17:11 Marek Aufart <notifications@github.com>:

**Comment by evgeny-chufarov** [comment]
Hi!
1. First of all you need to know the "provider_id" of your Infra OSP provider you want to map to. After making an Infra provider by POST request you will get a response where you can find its "provider_id".
`curl --user admin:smartvm -i -X POST -H "Accept: application/json" -d '{"type"      : 
 ManageIQ::Providers::Openstack::InfraManager", "name"      : "Infra_1","hostname"  : "XXX",
"port" : "5000", "api_version" : "v2", "security_protocol" : "non-ssl", "credentials" : {"userid"   : "admin","password" : "XXX"}}' http://localhost:3000/api/providers`
2. Then put this parameter among other attributes when making a new Cloud OSP provider. Like this:
"provider_id" : "ID"
`curl --user admin:smartvm -i -X POST -H "Accept: application/json" -d '{"type"      : "ManageIQ::Providers::Openstack::CloudManager","name"      : "Cloud_1","hostname"  : "XXX","port" : "5000", "provider_id" : "1", "api_version" : "v2", "security_protocol" : "non-ssl", "credentials" : {"userid"   : "admin","password" : "XXX"}}' http://localhost:3000/api/providers`

**Comment by izapolsk** [comment]
@evgeny-chufarov , many thanks ! 

@dkholodo , please add respective mapping to provider.create_rest(), since you're the most interested in this fix.

**Comment by dkholodo** [comment]
Hi,
I've added some code here [https://github.com/ManageIQ/integration_tests/blob/master/cfme/common/provider.py#L265](url)

`if self.type_name in ('openstack_infra', 'openstack'):
            import ipdb; ipdb.set_trace()
            if getattr(self, 'api_version', None):
                version = 'v3' if 'v3' in self.api_version else 'v2'
                provider_attributes['api_version'] = version
                if version == 'v3' and getattr(self, 'keystone_v3_domain_id', None):
                    provider_attributes['uid_ems'] = self.keystone_v3_domain_id
            if getattr(self, 'infra_provider', None):
                infra_providers_ids = self.get_all_provider_ids()
                if infra_providers_ids:
                    provider_attributes['provider_id'] = infra_providers_ids[0]`
________

ipdb> infra_providers_ids
[u'1000000000089', u'1000000000090']

ipdb> provider_attributes
{'provider_id': u'1000000000089', 'name': 'oc_ci', 'ipaddress': 'XXX', 'hostname': 'XXX', 'uid_ems': 'default', 'type': 'ManageIQ::Providers::Openstack::CloudManager', 'api_version': 'v3'}

But finally after cloud provider is created it is "Nothing selected" at the Openstack Infra Provider field [https://drive.google.com/open?id=1LQDBmLrd8S8VEzaHunyAjEI-kd5gTgF5](url)
Before adding my code this field was just blank [https://drive.google.com/open?id=1TACXGsyjjZHDLNbx3IFAZiF1C_hZeMSB](url)

So as far as I understood based on that that a field changed to "Nothing selected' it was an attempt to use provider_id but attempt was unsuccessful

Correct me please if I'm wrong and what else should be done? Am I using exactly that method for getting provider id or not?
Thanks.

**Comment by dkholodo** [comment]
Hi,
I've added some code here [https://github.com/ManageIQ/integration_tests/blob/master/cfme/common/provider.py#L265](url)

```
                if version == 'v3' and getattr(self, 'keystone_v3_domain_id', None):
                    provider_attributes['uid_ems'] = self.keystone_v3_domain_id
            if getattr(self, 'infra_provider', None):
                infra_providers_ids = self.get_all_provider_ids()
                if infra_providers_ids:
                    provider_attributes['provider_id'] = infra_providers_ids[0]
```
________

ipdb> infra_providers_ids
[u'1000000000089', u'1000000000090']

ipdb> provider_attributes
{'provider_id': u'1000000000089', 'name': 'oc_ci', 'ipaddress': 'XXX', 'hostname': 'XXX', 'uid_ems': 'default', 'type': 'ManageIQ::Providers::Openstack::CloudManager', 'api_version': 'v3'}

But finally after cloud provider is created it is "Nothing selected" at the Openstack Infra Provider field [https://drive.google.com/open?id=1LQDBmLrd8S8VEzaHunyAjEI-kd5gTgF5](url)
Before adding my code this field was just blank [https://drive.google.com/open?id=1TACXGsyjjZHDLNbx3IFAZiF1C_hZeMSB](url)

So as far as I understood based on that that a field changed to "Nothing selected' it was an attempt to use provider_id but attempt was unsuccessful

Correct me please if I'm wrong and what else should be done? Am I using exactly that method for getting provider id or not?
Thanks in advance.

**Comment by dkholodo** [comment]
Hi,
I've added some code here https://github.com/ManageIQ/integration_tests/blob/master/cfme/common/provider.py#L265

                if version == 'v3' and getattr(self, 'keystone_v3_domain_id', None):
                    provider_attributes['uid_ems'] = self.keystone_v3_domain_id
            if getattr(self, 'infra_provider', None):
                infra_providers_ids = self.get_all_provider_ids()
                if infra_providers_ids:
                    provider_attributes['provider_id'] = infra_providers_ids[0]
ipdb> infra_providers_ids
[u'1000000000089', u'1000000000090']

ipdb> provider_attributes
{'provider_id': u'1000000000089', 'name': 'oc_ci', 'ipaddress': 'XXX', 'hostname': 'XXX', 'uid_ems': 'default', 'type': 'ManageIQ::Providers::Openstack::CloudManager', 'api_version': 'v3'}

But finally after cloud provider is created it is "Nothing selected" at the Openstack Infra Provider field https://drive.google.com/open?id=1LQDBmLrd8S8VEzaHunyAjEI-kd5gTgF5
Before adding my code this field was just blank https://drive.google.com/open?id=1TACXGsyjjZHDLNbx3IFAZiF1C_hZeMSB

So as far as I understood based on that that a field changed to "Nothing selected' it was an attempt to use provider_id but attempt was unsuccessful

Correct me please if I'm wrong and what else should be done? Am I using exactly that method for getting provider id or not?
Thanks in advance.

**Comment by mfeifer** [comment]
@aufi is there an update on this?

**Comment by aufi** [comment]
No, I think we can close this,
