### ISSUE TITLE
Unknown OpenStack instances displayed as  either "Unknown" or "unknown"

### ISSUE THREAD

**Issue by tjyang** [ManageIQ/manageiq-providers-openstack#320]
*  Gapri-4 in a local region.
*  I remember  that issue was due to typo in provider or [manageiq source tree](https://github.com/ManageIQ/manageiq/search?p=2&q=Unknown&unscoped_q=Unknown).
   * I fixed it by making unknown to Unknown before. Need to locate the src again.
* Screenshot
![image](https://user-images.githubusercontent.com/378638/42937252-177e7d72-8b14-11e8-95f7-5a3fd53c3a66.png)

**Comment by Ladas** [comment]
@aufi ^

**Comment by JPrause** [comment]
@tjyang is this still a valid issue? If yes, let me know and I'll remove the stale label. If not can you close.
If there's no update by next week, I'll be closing this issue.

**Comment by tjyang** [comment]
@JPrause , This issue is be classify as bug and with assignee. Please follow up with assignee.

**Comment by JPrause** [comment]
Thanks @tjyang for the update. I'll remove the stale label.
@miq-bot remove_label stale
@evgeny-chufarov do you have an update on this issue?

**Comment by evgeny-chufarov** [comment]
@JPrause 
Unfortunately, I couldn't reproduce this bug in time when I tried to solve it.
I will try to do it again and solve this issue. 
I will let you know, if I haven't any solutions.

**Comment by evgeny-chufarov** [comment]
@tjyang Could you tell me please, if this "unknown", that you have found and corrected once, was this blue one on the screenshot of PR?

**Comment by mfeifer** [comment]
@aufi can you take a look at this?
