### ISSUE TITLE
Duplicate method names for Cloud Tenant 

### ISSUE THREAD

**Issue by andyvesel** [ManageIQ/manageiq-providers-openstack#34]
We have a [CRUD methods](https://github.com/andyvesel/manageiq-providers-openstack/blob/master/app/models/manageiq/providers/openstack/cloud_manager/cloud_tenant.rb#L15) for Cloud Tenant base model in this repo. 

Also we have a [methods](https://github.com/ManageIQ/manageiq/blob/master/app/models/cloud_tenant.rb#L40) with identical names but different body in a Cloud Tenant model for a main repo.
Do we want to remove those methods from this repo? Which ones of those methods do we actually use and need to keep?

**Comment by aufi** [comment]
This example with CloudTenant methods looks to be correct for me. Are there other object methods looking wrong?

**Comment by andyvesel** [comment]
Yes, it seems like there's neither any mistake here, nor any other objects wrong. So, I'm closing the issue.
