### ISSUE TITLE
Repeated queries to Heat for stacks in the same tenant during NetworkManager refresh

### ISSUE THREAD

**Issue by adamgoossens** [ManageIQ/manageiq-providers-openstack#340]
Hi everyone,

Making an issue to track the PR I've opened here:

https://github.com/ManageIQ/manageiq-providers-openstack/pull/339

**What I see:**
In short: in environments where there are no orchestration stacks we always receive an empty list of stacks back from the provider. Because we always go back to the provider to refresh if the associated attribute is an empty list, this means we can query Heat multiple times.

In a QA environment I've seen the NetworkManager refresh drag on for 45-50 minutes with multiple  requests to Heat every second, each one for the stacks for one of the projects in my environment.

This is because we also attempt to find the parent orchestration stack for every security group and cloud network in the environment. Each search of the stacks for each security group/cloud network therefore triggers a fresh fetch of all stacks from Heat, ballooning the length of the refresh timings and causing the repeated queries.

**What should happen**
NetworkManager should only query once for the stacks for a project during the lifetime of its collector.

After applying the attached PR, the refresh timings dropped back to normal (~60 seconds).

This only occurs when there are no stacks in the environment anywhere. Having even a single one works around that problem.

**Comment by gildub** [comment]
Thanks @adamgoossens for this slick approach.

**Comment by mansam** [comment]
I believe this was resolved by https://github.com/ManageIQ/manageiq-providers-openstack/pull/339
