### ISSUE TITLE
Spec: Need test sets for network manager

### ISSUE THREAD

**Issue by gildub** [ManageIQ/manageiq-providers-openstack#36]
Support is required for network_manager related tests for the following:

- [x] Network provider structure and provisioning 
- [x] Network Router
- [x] Cloud Network
- [x] Cloud Subnet
- [x] Security Groups
- [x] Security Groups rules
- [x] Floating IPs

**Comment by gildub** [comment]
@Ladas ,

The network manager is a bit of an hybrid as compared to the cloud and infra ones.
Do you have requirement ideas and recommendations for the `spec/models/manageiq/providers/openstack/network_manager/`?

Thanks

**Comment by Ladas** [comment]
@gildub yeah I suppose the spec/models/manageiq/providers/openstack/network_manager/ should work, we are using the same in AWS

**Comment by gildub** [comment]
@Ladas,  ok, thanks

**Comment by gildub** [comment]
https://github.com/ManageIQ/manageiq-providers-openstack/pull/37

**Comment by JPrause** [comment]
@gildub is this still a valid issue? If yes, let me know and I'll remove the stale label. If not can you close.
If there's no update by next week, I'll be closing this issue.

**Comment by gildub** [comment]
@JPrause, I suppose it is, not sure who's going to have time to address them though.

**Comment by JPrause** [comment]
Thanks @gildub 
I'll remove the stale flag for now.
@miq-bot remove_label stale
