### ISSUE TITLE
Minimize require dependencies in code

### ISSUE THREAD

**Issue by aufi** [ManageIQ/manageiq-providers-openstack#51]
We imported code from several ManageIQ repositories. There are some legacy parts which should be refactored. We should start with removing not needed dependecies and possibly remove ```require "..."``` from ruby files where is it not really needed.

**Comment by JPrause** [comment]
@aufi is this still a valid issue? If yes, let me know and I'll remove the stale label. If not can you close.
If there's no update by next week, I'll be closing this issue.

**Comment by mfeifer** [comment]
Please open more specific issues as needed.
