### ISSUE TITLE
CLI for ManageIQ - do we want it?

### ISSUE THREAD

**Issue by andyvesel** [ManageIQ/manageiq-providers-openstack#622]
Just curios, what Manageiq folks think about if we'd have a console tool for fetching provider resources with miq api. The idea is -  simply do in console what api allows us to do: controlling provider (Openstack in this case), instance operations, etc...
I saw some repos like https://github.com/rhpit/manageiq-cli or https://github.com/juliancheal/ManageIQ-Cli, they don't seem to be supported for a long time (haven't tried it though).
Actually, this question is not really about "do we need it or not" (I have it as a personal project for learning golang). It's more about sharing some ideas, what to do and what is not to do. I'd appreciate any of your thoughts.
Thanks!

**Comment by Fryguy** [comment]
I started putting together a cli that was more about deployment.  I never thought of a cli for fetching data though, which is interesting. Even so, we already have a cli that can fetch data from the API (see the manageiq-api-client repo), so if users need data they can use that.
