### ISSUE TITLE
Provider registration "Validate" button does not activate

### ISSUE THREAD

**Issue by jaywcarman** [ManageIQ/manageiq-providers-openstack#635]
When registering a new OpenStack Cloud Provider the "Validate" button does not activate despite all required fields being populated. This form was working 19 days ago (see #630 hehe). I'm guessing something got broken when the DDF schema was recently updated in #626.

![image](https://user-images.githubusercontent.com/1637291/93339328-0f0e5d00-f7f1-11ea-9923-0bfc204a7f34.png)

**Comment by agrare** [comment]
I think @skateman has a fix for this issue

**Comment by skateman** [comment]
Yeah, this is the same issue as https://github.com/ManageIQ/manageiq-providers-ovirt/issues/522, there's a fix but the CI is red on it https://github.com/ManageIQ/manageiq-ui-classic/pull/7308

**Comment by jaywcarman** [comment]
Great, I'll subscribe to the manageiq-ui-classic fix. Thanks for the quick response!

**Comment by skateman** [comment]
Tests are green, just waiting someone to merge it...

**Comment by skateman** [comment]
@miq-bot close_issue
Resolved via https://github.com/ManageIQ/manageiq-ui-classic/pull/7308
