### ISSUE TITLE
NetworkRouter administration state should be a boolean

### ISSUE THREAD

**Issue by skateman** [ManageIQ/manageiq-providers-openstack#680]
The `NetworkRouter#admin_state_up` is stored either as a `'t'` string or a `nil` value. This makes the DDF conversion problemmatic as we can't easily convert this value into a checkbox/switch. @agrare would it be possible to at least have a virtual column (queryable via the API) that returns a boolean (or nil) value?

@miq-bot add_label question
Parent issue: https://github.com/ManageIQ/manageiq-ui-classic/issues/6862

**Comment by skateman** [comment]
@miq-bot assign @agrare

**Comment by agrare** [comment]
That is strange, the openstack API returns this as a boolean but our column is varchar for some reason.  I think we should do a schema migration to make this a proper boolean column.

**Comment by skateman** [comment]
Any update on this?
