### ISSUE TITLE
Remove openstack handle code from manageiq-gems-pending

### ISSUE THREAD

**Issue by Fryguy** [ManageIQ/manageiq-providers-openstack#7]
Now that the Openstack provider has its own repo, it's time to move the openstack specific code from manageiq-gems-pending to here.  See https://github.com/ManageIQ/manageiq-gems-pending/tree/master/lib/gems/pending/openstack.

Additionally there is https://github.com/ManageIQ/manageiq-gems-pending/tree/master/lib/gems/pending/OpenStackExtract/MiqOpenStackVm , which should also probably come over, but I'm not sure the smart state code can handle moving that as I'm not sure how that interacts.  If it can move over as well that would be preferable.

**Comment by aufi** [comment]
@miq-bot assign aufi

**Comment by chessbyte** [comment]
@aufi @tzumainn Please extract `https://github.com/ManageIQ/manageiq-gems-pending/tree/master/lib/gems/pending/openstack`.

I am in the process of extracting `https://github.com/ManageIQ/manageiq-gems-pending/tree/master/lib/gems/pending/OpenStackExtract` to a new `manageiq-smartstate` repo.

**Comment by aufi** [comment]
@chessbyte Yes, I will do that. Thanks for clarification.

**Comment by Fryguy** [comment]
@aufi The smartstate code has been extracted from manageiq-gems-pending into manageiq-smartstate.

**Comment by aufi** [comment]
The code was removed in https://github.com/ManageIQ/manageiq-gems-pending/pull/119
