### ISSUE TITLE
fine-3 showing gnocchi port(8041) connection refused

### ISSUE THREAD

**Issue by tjyang** [ManageIQ/manageiq-providers-openstack#75]
Following message keep logging into miq fine-3's evm.log,since we don't have gnocchi enabled.

```
[----] E, [2017-08-04T10:57:40.499019 #3200:1163130] ERROR -- : <Fog> excon.error     #<Excon::Error::Socket: Connection refused - connect(2) for 1xx.xx.82.11:8041 (Errno::ECONNREFUSED)>

[----] E, [2017-08-04T10:57:40.565602 #3186:1163130] ERROR -- : <Fog> excon.error     #<Excon::Error::Socket: Connection refused - connect(2) for 1xx.xx.82.11:8041 (Errno::ECONNREFUSED)>

```

Is there a way in settings.yml file to disable it ?

**Comment by tzumainn** [comment]
@mansam did you have a PR that prevented these messages from showing up?

**Comment by mansam** [comment]
This should have been resolved by a change to the FogLogger a while back.

**Comment by JPrause** [comment]
@tjyang is this still a valid issue? If yes, let me know and I'll remove the stale label. If not can you close.
If there's no update by next week, I'll be closing this issue.
