### ISSUE TITLE
Targeted refresh not working for OpenStack (Train) provider

### ISSUE THREAD

**Issue by AlexonOliveiraRH** [ManageIQ/manageiq-providers-openstack#751]
The `:ems_refresh:` is set with `:allow_targeted_refresh: true` and `:refresh_interval: 15.minutes` for the OpenStack provider, like the following:

~~~
:openstack:
       :is_admin: false
       :heat:
       :is_global_admin: false
       :inventory_object_refresh: true
       :allow_targeted_refresh: true
       :parallel_thread_limit: 0
       :refresh_interval: 15.minutes
:openstack_network:
       :is_admin: false
       :inventory_object_refresh: true
       :allow_targeted_refresh: true
       :refresh_interval: 15.minutes
:cinder:
       :is_admin: false
       :inventory_object_refresh: true
       :allow_targeted_refresh: true
       :refresh_interval: 15.minutes
~~~

But targeted refresh is not working, only full refreshes. No `EventCatcher` is shown in the `evm.log` file.

The CFME version is 5.11.11.0 and CloudForms version is 5.0 (ManageIQ Ivanchuk). Legacy telemetry (Ceilometer, Gnocchi, Aodh and Panko) are being used in the RHOSP 16.1 (OpenStack Train) environment.

**Comment by daniloperogil** [comment]
Hello,

Here are the Workers outputs.

#######
[root@cf103 vmdb]# rake evm:status
Checking EVM status...
 Region | Zone          | Server     | Status  |  PID |   SPID | Workers | Version   | Started    | Heartbeat   | MB Usage | Roles
--------+---------------+------------+---------+------+--------+---------+-----------+------------+-------------+----------+--------------------------------------------------------------------------------
      1 | RTM - Zone SP | cf103 - WK | started | 3937 | 695703 |      23 | 5.11.11.0 | 2021-08-13 | 13:14:50UTC |      284 | automate:embedded_ansible:ems_operations:event:scheduler:smartproxy:smartstate

* marks a master appliance

 Type                                     | Status  |     PID |    SPID | Queue             | Started    | Heartbeat   | MB Usage
------------------------------------------+---------+---------+---------+-------------------+------------+-------------+----------
 EventHandler                             | started |    8916 |    3643 | ems               | 2021-08-13 | 13:14:42UTC | 272/500
 Generic                                  | started |    7242 |    2437 | generic           | 2021-08-13 | 13:14:43UTC | 866/1536
 Generic                                  | started |    7250 |    2438 | generic           | 2021-08-13 | 13:14:42UTC | 863/1536
 Generic                                  | started |    7258 |    2441 | generic           | 2021-08-13 | 13:14:42UTC | 843/1536
 Generic                                  | started |  226030 | 2872902 | generic           | 2021-09-28 | 13:14:43UTC | 842/1536
 Generic                                  | started | 1088144 | 3366178 | generic           | 2021-10-07 | 13:14:43UTC | 825/1536
 Generic                                  | started | 2023795 | 1368928 | generic           | 2021-09-03 | 13:14:42UTC | 887/1536
 Generic                                  | started | 2516642 |   15259 | generic           | 2021-10-22 | 13:14:43UTC | 852/1536
 Generic                                  | started | 3844299 | 2541491 | generic           | 2021-09-22 | 13:14:43UTC | 866/1536
 Openstack::Cloud::EventCatcher           | started |    8892 |    3649 | ems_1000000000004 | 2021-08-13 | 13:14:33UTC | 306/2048
 Openstack::Network::EventCatcher         | started |    8900 |    3654 | ems_1000000000005 | 2021-08-13 | 13:14:39UTC | 306/2048
 Openstack::Storage::Cinder::EventCatcher | started |    8908 |    3655 | ems_1000000000002 | 2021-08-13 | 13:14:38UTC | 307/2048
 Priority                                 | started |    7340 |    2520 | generic           | 2021-08-13 | 13:14:45UTC | 384/1536
 Priority                                 | started |    7348 |    2522 | generic           | 2021-08-13 | 13:14:45UTC | 382/1536
 Priority                                 | started |    7356 |    2521 | generic           | 2021-08-13 | 13:14:44UTC | 385/1536
 Priority                                 | started |    7372 |    2524 | generic           | 2021-08-13 | 13:14:45UTC | 372/1536
 Priority                                 | started |    7380 |    2525 | generic           | 2021-08-13 | 13:14:45UTC | 386/1536
 Priority                                 | started |    7388 |    2526 | generic           | 2021-08-13 | 13:14:44UTC | 397/1536
 Priority                                 | started |    7396 |    2527 | generic           | 2021-08-13 | 13:14:45UTC | 384/1536
 Priority                                 | started | 1830832 | 1237425 | generic           | 2021-09-01 | 13:14:44UTC | 394/1536
 Schedule                                 | started |    7203 |    2323 |                   | 2021-08-13 | 13:14:39UTC | 434/500
 SmartProxy                               | started |    8928 |    3645 | smartproxy        | 2021-08-13 | 13:14:44UTC | 272/2048
 SmartProxy                               | started |    8937 |    3644 | smartproxy        | 2021-08-13 | 13:14:43UTC | 272/2048

All rows have the values: Region=1, Zone=RTM - Zone SP, Server=cf103 - WK


#######
[root@cf104 vmdb]# rake evm:status
Checking EVM status...                                                                                                                                                                      r
 Region | Zone          | Server      | Status  |  PID |   SPID | Workers | Version   | Started    | Heartbeat   | MB Usage | Roles
--------+---------------+-------------+---------+------+--------+---------+-----------+------------+-------------+----------+-------------------------------------------------------------------------
      1 | RTM - Zone SP | cf104 - WK* | started | 4022 | 695606 |      19 | 5.11.11.0 | 2021-08-13 | 13:14:49UTC |      287 | automate:embedded_ansible:ems_operations:notifier:smartproxy:smartstate

* marks a master appliance

 Type       | Status  |     PID |    SPID | Queue      | Started    | Heartbeat   | MB Usage
------------+---------+---------+---------+------------+------------+-------------+----------
 Generic    | started |    6592 |    2454 | generic    | 2021-08-13 | 13:14:43UTC | 929/1536
 Generic    | started |  580944 | 3967053 | generic    | 2021-10-18 | 13:14:41UTC | 856/1536
 Generic    | started |  873423 |   16039 | generic    | 2021-10-22 | 13:14:42UTC | 843/1536
 Generic    | started | 2974023 | 2495780 | generic    | 2021-09-21 | 13:14:42UTC | 837/1536
 Generic    | started | 3013188 | 2527869 | generic    | 2021-09-22 | 13:14:42UTC | 878/1536
 Generic    | started | 3172990 | 2657921 | generic    | 2021-09-24 | 13:14:41UTC | 876/1536
 Generic    | started | 3856994 | 3205627 | generic    | 2021-10-04 | 13:14:42UTC | 881/1536
 Generic    | started | 4045984 | 3362278 | generic    | 2021-10-07 | 13:14:43UTC | 812/1536
 Priority   | started |    6608 |    2436 | generic    | 2021-08-13 | 13:14:44UTC | 378/1536
 Priority   | started |    6624 |    2439 | generic    | 2021-08-13 | 13:14:43UTC | 389/1536
 Priority   | started |    6648 |    2455 | generic    | 2021-08-13 | 13:14:43UTC | 394/1536
 Priority   | started |    6657 |    2452 | generic    | 2021-08-13 | 13:14:43UTC | 399/1536
 Priority   | started |    6665 |    2453 | generic    | 2021-08-13 | 13:14:44UTC | 394/1536
 Priority   | started | 2648264 | 1485691 | generic    | 2021-11-17 | 13:14:43UTC | 354/1536
 Priority   | started | 2648288 | 1485693 | generic    | 2021-11-17 | 13:14:44UTC | 352/1536
 Priority   | started | 3997044 | 3322093 | generic    | 2021-10-06 | 13:14:44UTC | 386/1536
 Schedule   | started |    6533 |    2321 |            | 2021-08-13 | 13:14:39UTC | 285/500
 SmartProxy | started |    6745 |    2486 | smartproxy | 2021-08-13 | 13:14:42UTC | 281/2048
 SmartProxy | started |    6753 |    2488 | smartproxy | 2021-08-13 | 13:14:43UTC | 280/2048

All rows have the values: Region=1, Zone=RTM - Zone SP, Server=cf104 - WK


#######
[root@cf107 vmdb]# rake evm:status                                                                                                                                                          -
Checking EVM status...
 Region | Zone          | Server     | Status  |   PID |   SPID | Workers | Version   | Started    | Heartbeat   | MB Usage | Roles                                                         r
--------+---------------+------------+---------+-------+--------+---------+-----------+------------+-------------+----------+------------------------------------------------------------------------------                                                                                                                                                                              -
      1 | RTM - Zone SP | cf107 - WK | started | 34214 | 695146 |      22 | 5.11.11.0 | 2021-08-13 | 13:14:42UTC |      283 | automate:embedded_ansible:ems_inventory:ems_operations:smartproxy:smartstate                                                                                                                                                                               m

* marks a master appliance

 Type                            | Status  |     PID |    SPID | Queue                                                                   | Started    | Heartbeat   | MB Usage
---------------------------------+---------+---------+---------+-------------------------------------------------------------------------+------------+-------------+------------
 Foreman::Configuration::Refresh | started |   36467 |    2328 | ems_1000000000006                                                       | 2021-08-13 | 13:14:49UTC | 311/10240
 Foreman::Provisioning::Refresh  | started |   36475 |    2329 | ems_1000000000007                                                       | 2021-08-13 | 13:14:47UTC | 300/10240
 Generic                         | started |   36556 |    2459 | generic                                                                 | 2021-08-13 | 13:14:54UTC | 864/1536
 Generic                         | started |   36618 |    2493 | generic                                                                 | 2021-08-13 | 13:14:53UTC | 867/1536
 Generic                         | started | 1024154 | 1237439 | generic                                                                 | 2021-09-01 | 13:14:52UTC | 851/1536
 Generic                         | started | 1377738 | 1685612 | generic                                                                 | 2021-09-08 | 13:14:53UTC | 867/1536
 Generic                         | started | 2102085 | 2542490 | generic                                                                 | 2021-09-22 | 13:14:53UTC | 897/1536
 Generic                         | started | 2533541 | 2982705 | generic                                                                 | 2021-09-30 | 13:14:52UTC | 829/1536
 Generic                         | started | 2858403 | 3322190 | generic                                                                 | 2021-10-06 | 13:14:52UTC | 864/1536
 Generic                         | started | 3613850 | 4109067 | generic                                                                 | 2021-10-20 | 13:14:52UTC | 823/1536
 Openstack::Cloud::Refresh       | started |   36483 |    2341 | ems_1000000000002:ems_1000000000003:ems_1000000000004:ems_1000000000005 | 2021-08-13 | 13:10:49UTC | 1098/10240
 Priority                        | started |   36632 |    2536 | generic                                                                 | 2021-08-13 | 13:14:54UTC | 386/1536
 Priority                        | started |   36656 |    2538 | generic                                                                 | 2021-08-13 | 13:14:54UTC | 387/1536
 Priority                        | started |   36688 |    2543 | generic                                                                 | 2021-08-13 | 13:14:55UTC | 400/1536
 Priority                        | started | 1024046 | 1237417 | generic                                                                 | 2021-09-01 | 13:14:54UTC | 390/1536
 Priority                        | started | 1024066 | 1237419 | generic                                                                 | 2021-09-01 | 13:14:54UTC | 386/1536
 Priority                        | started | 1024104 | 1237430 | generic                                                                 | 2021-09-01 | 13:14:54UTC | 388/1536
 Priority                        | started | 1024196 | 1237445 | generic                                                                 | 2021-09-01 | 13:14:54UTC | 382/1536
 Priority                        | started | 2858343 | 3322091 | generic                                                                 | 2021-10-06 | 13:14:54UTC | 380/1536
 Schedule                        | started |   36492 |    2327 |                                                                         | 2021-08-13 | 13:14:52UTC | 274/500
 SmartProxy                      | started |   37272 |    3388 | smartproxy                                                              | 2021-08-13 | 13:14:54UTC | 272/2048
 SmartProxy                      | started |   37280 |    3390 | smartproxy                                                              | 2021-08-13 | 13:14:54UTC | 272/2048
                                                                                                                                                                                            2
All rows have the values: Region=1, Zone=RTM - Zone SP, Server=cf107 - WK




Best.

**Comment by agrare** [comment]
Thank you, so it appears the event catchers are running on appliance cf103:
```
Openstack::Cloud::EventCatcher | started | 8892 | 3649 | ems_1000000000004 | 2021-08-13 | 13:14:33UTC | 306/2048
Openstack::Network::EventCatcher | started | 8900 | 3654 | ems_1000000000005 | 2021-08-13 | 13:14:39UTC | 306/2048
Openstack::Storage::Cinder::EventCatcher | started | 8908 | 3655 | ems_1000000000002 | 2021-08-13 | 13:14:38UTC | 307/2048
```

Can you run `grep '#8892 /var/www/miq/vmdb/log/evm.log` on that cf103 appliance and post the results?  Thanks!

**Comment by daniloperogil** [comment]
Hello,

Follow the outputs.

[----] I, [2021-11-22T10:57:16.898936 #8892:2ad3b6f0e54c]  INFO -- : Querying OpenStack for events newer than ...
[----] I, [2021-11-22T10:57:31.967000 #8892:2ad3b6f0e54c]  INFO -- : Querying OpenStack for events newer than ...
[----] I, [2021-11-22T10:57:47.029489 #8892:2ad3b6f0e54c]  INFO -- : Querying OpenStack for events newer than ...
[----] I, [2021-11-22T10:58:02.083940 #8892:2ad3b6f0e54c]  INFO -- : Querying OpenStack for events newer than ...
[----] I, [2021-11-22T10:58:17.142986 #8892:2ad3b6f0e54c]  INFO -- : Querying OpenStack for events newer than ...
[----] I, [2021-11-22T10:58:32.221492 #8892:2ad3b6f0e54c]  INFO -- : Querying OpenStack for events newer than ...
[----] I, [2021-11-22T10:58:32.221492 #8892:2ad3b6f0e54c]  INFO -- : Querying OpenStack for events newer than ...
[----] I, [2021-11-22T10:58:35.847378 #8892:2ad3b67ae5b8]  INFO -- : MIQ(ManageIQ::Providers::Openstack::CloudManager::EventCatcher::Runner#message_sync_config) EMS [cloud.rtmcloud.net.br]
 as [admin] Synchronizing configuration...
[----] I, [2021-11-22T10:58:35.988667 #8892:2ad3b67ae5b8]  INFO -- : MIQ(ManageIQ::Providers::Openstack::CloudManager::EventCatcher::Runner#sync_config) ID [1000000026863], PID [8892], GUI
D [42633897-2879-4dd6-aaa2-b6c865e09ad5], Zone [RTM - Zone SP], Active Roles [automate,embedded_ansible,ems_operations,event,scheduler,smartproxy,smartstate], Assigned Roles [automate,data
base_owner,embedded_ansible,ems_inventory,ems_operations,event,notifier,scheduler,smartproxy,smartstate], Configuration:
[----] I, [2021-11-22T10:58:35.989251 #8892:2ad3b67ae5b8]  INFO -- :
[----] I, [2021-11-22T10:58:35.989293 #8892:2ad3b67ae5b8]  INFO -- : ---
[----] I, [2021-11-22T10:58:35.989434 #8892:2ad3b67ae5b8]  INFO -- :
[----] I, [2021-11-22T10:58:35.989499 #8892:2ad3b67ae5b8]  INFO -- : MIQ(ManageIQ::Providers::Openstack::CloudManager::EventCatcher::Runner#message_sync_config) EMS [cloud.rtmcloud.net.br]
 as [admin] Synchronizing configuration complete...
[----] I, [2021-11-22T10:58:47.296994 #8892:2ad3b6f0e54c]  INFO -- : Querying OpenStack for events newer than ...
[----] I, [2021-11-22T10:59:02.375944 #8892:2ad3b6f0e54c]  INFO -- : Querying OpenStack for events newer than ...
[----] I, [2021-11-22T10:59:17.449934 #8892:2ad3b6f0e54c]  INFO -- : Querying OpenStack for events newer than ...
[----] I, [2021-11-22T10:59:32.516023 #8892:2ad3b6f0e54c]  INFO -- : Querying OpenStack for events newer than ...
[----] I, [2021-11-22T10:59:47.581948 #8892:2ad3b6f0e54c]  INFO -- : Querying OpenStack for events newer than ...
[----] I, [2021-11-22T11:00:02.930961 #8892:2ad3b6f0e54c]  INFO -- : Querying OpenStack for events newer than ...
[----] I, [2021-11-22T11:00:18.010976 #8892:2ad3b6f0e54c]  INFO -- : Querying OpenStack for events newer than ...
[----] I, [2021-11-22T11:00:33.074942 #8892:2ad3b6f0e54c]  INFO -- : Querying OpenStack for events newer than ...
[----] I, [2021-11-22T11:00:48.139991 #8892:2ad3b6f0e54c]  INFO -- : Querying OpenStack for events newer than ...
[----] I, [2021-11-22T11:01:03.204027 #8892:2ad3b6f0e54c]  INFO -- : Querying OpenStack for events newer than ...


Best.

**Comment by agrare** [comment]
Okay it appears that the event query is not failing, but it also never returns any events.

That log line should include the timestamp of the last event that was returned, or `nil` if it is the first query.  From that it appears that `@since` is always `nil`.

Seems something might be wrong with the ceilometer service?

**Comment by AlexonOliveiraRH** [comment]
@agrare, Ceilometer `polling_interval` is configured to 300s. We did different tests within OSP regarding alarming and other stuff that makes use of Ceilometer and it works pretty well, although it needs some timing adjustments that will be done soon. I don't know if you could answer that, but what kind of issues are looking for in Ceilometer if that's the case?

**Comment by agrare** [comment]
Honestly I don't know, this is probably where we need to pull @andyvesel or someone with more backend openstack expertise.

From a MIQ core point of view we are running the worker and it is querying for events, after that it is an openstack provider / openstack concern.

**Comment by AlexonOliveiraRH** [comment]
@agrare, got it. @andyvesel, could you give us a hand on this?

**Comment by AlexonOliveiraRH** [comment]
Hey @andyvesel, any thoughts?
