### ISSUE TITLE
Snapshots without a vm_or_template association break inventory refresh

### ISSUE THREAD

**Issue by jaywcarman** [ManageIQ/manageiq-providers-openstack#844]
In OpenStack a snapshot is just an image with associated metadata. The inventory parser uses the following `snapshot?` method to determine if an image is a snapshot:
https://github.com/ManageIQ/manageiq-providers-openstack/blob/84df8ce487e0d92fde6cc296daf6fff4acd40f67/app/models/manageiq/providers/openstack/inventory/parser/cloud_manager.rb?plain=1#L257-L268

If an image is determined to be a snapshot, it is persisted using a `lazy_find` to retrieve it's parent `vm_or_template` id:
https://github.com/ManageIQ/manageiq-providers-openstack/blob/84df8ce487e0d92fde6cc296daf6fff4acd40f67/app/models/manageiq/providers/openstack/inventory/parser/cloud_manager.rb?plain=1#L247

The problem is that these snapshots will remain (as images) even after the associated VM has been removed. When this happens `:vm_or_template` will be `nil` and the inventory refresh will fail with an "Referential integrity check violated for [the snapshot] because of missing foreign key vm_or_template_id".

I found this issue using the manageiq-providers-ibm_power_vc provider, which inherits this inventory collection code from manageiq-providers-openstack. @agrare was able to recreate using a test Microstack environment. Here's the backtrace from my PowerVC environment:
```
/home/jwcarman/src/github.com/ManageIQ/manageiq/app/models/manageiq/providers/base_manager/refresher.rb:68:in `refresh': Referential integrity check violated for {:uid=>"02c1c88a-0b28-4806-aa15-9d5d679e6c31", :vm_or_template_id=>nil, :name=>"yus-tf-helper_Image", :uid_ems=>"02c1c88a-0b28-4806-aa15-9d5d679e6c31", :ems_ref=>"02c1c88a-0b28-4806-aa15-9d5d679e6c31", :create_time=>"2023-03-21T04:32:47Z", :description=>nil} of InventoryCollection:<ManageIQ::Providers::IbmPowerVc::CloudManager::Snapshot> because of missing foreign key vm_or_template_id for ManageIQ::Providers::IbmPowerVc::CloudManager:2 (ManageIQ::Providers::BaseManager::Refresher::PartialRefreshError)
	from /home/jwcarman/src/github.com/ManageIQ/manageiq/app/models/manageiq/providers/base_manager/refresher.rb:11:in `refresh'
	from /home/jwcarman/src/github.com/ManageIQ/manageiq/app/models/ems_refresh.rb:71:in `block in refresh'
	from /home/jwcarman/src/github.com/ManageIQ/manageiq/app/models/ems_refresh.rb:70:in `each'
	from /home/jwcarman/src/github.com/ManageIQ/manageiq/app/models/ems_refresh.rb:70:in `refresh'
	from (irb):3:in `<main>'
	from /home/jwcarman/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/railties-6.1.7.3/lib/rails/commands/console/console_command.rb:70:in `start'
	from /home/jwcarman/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/railties-6.1.7.3/lib/rails/commands/console/console_command.rb:19:in `start'
	from /home/jwcarman/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/railties-6.1.7.3/lib/rails/commands/console/console_command.rb:102:in `perform'
	from /home/jwcarman/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /home/jwcarman/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /home/jwcarman/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /home/jwcarman/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/railties-6.1.7.3/lib/rails/command/base.rb:69:in `perform'
	from /home/jwcarman/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/railties-6.1.7.3/lib/rails/command.rb:48:in `invoke'
	from /home/jwcarman/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/railties-6.1.7.3/lib/rails/commands.rb:18:in `<main>'
	from /home/jwcarman/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /home/jwcarman/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	... 1 levels...
```

**Comment by agrare** [comment]
This exception comes from the `assert_graph_integrity` check which ensures that any "required" foreign_keys that are components of the `manager_ref` are present.  In development/test this defaults to a `raise` and in production this defaults to a warn.

I mentioned "required" foreign_keys because we also have the option for "optional" components of the manager_ref.  If the `uid` is sufficiently unique and the `vm_or_template` is optional then we can say that it is okay for `vm_or_template_id` to be `nil`.
